analytics: {}
color:
  brandColors:
    - '#B8C0C0'
    - '#000000'
    - '#787878'
    - '#000000'
    - '#000000'
  brandStrength: 0.034628
  lightness: 0
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 1
name: ktisis
opengraph: {}
purpose: {}
typography_spectrum: 0.274493
