analytics: {}
color:
  brandColors:
    - '#B8C0C0'
    - '#000000'
    - '#787878'
    - '#000000'
    - '#000000'
  brandStrength: 0.429899
  lightness: 0.498311
  rhythmicContrast: 0.480574
  saturation: 0.300676
cta: {}
layout_spectrum: 1
name: ktisis
opengraph: {}
purpose: {}
typography_spectrum: 0.274493
